version: 0.1
run-as: root

phases:
  install:
    commands:
      - n 14.0.0
      - npm install -g serverless

  pre_build:
    commands:
      - echo Build started
      - GOOS=linux go build -o bin/Main main.go
      - echo Build ended
  build:
    commands:
      - serverless deploy --param="stage=main" --param="region=${AWS_REGION}"
      - echo Deployed successfully
artifacts:
  files:
    - '**/*'