service: sepet

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  deploymentBucket:
    name: sepet-deployment-bucket-eu-central-1
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

plugins:
  - serverless-deployment-bucket

package:
  patterns:
    - '!./**'
    - ./bin/**
iamRoleStatements:
  - Effect: Allow
    Action:
      - "apigateway:*"
    Resource: "*"
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:ListTables
      - dynamodb:DescribeTables
    Resource: "*"
functions:
  main-module:
    handler: bin/Main
    environment:
      ENVIRONMENT: aws
      SERVICE_STAGE_NAME: sepet-main
    events:
      - http:
          path: /add-product
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /remove-product
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /empty-cart
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /get-cart
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /update-product
          method: post
          cors:
            origin: '*'
            headers: '*'

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: sepet-app-Users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: N
          - AttributeName: cartId
            AttributeType: N
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
    CartTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sepet-app-Carts
        AttributeDefinitions:
          - AttributeName: cartId
            AttributeType: N
          - AttributeName: cartItems
            AttributeType: L
          - AttributeName: userId
            AttributeType: N
        KeySchema:
          - AttributeName: cartId
            KeyType: HASH
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sepet-app-Products
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: N
          - AttributeName: brand
            AttributeType: S
          - AttributeName: productName
            AttributeType: S
          - AttributeName: stock
            AttributeType: N
          - AttributeName: Price
            AttributeType: S
          - AttributeName: description
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH