service: sepet

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  deploymentBucket:
    name: sepet-deployment-bucket-eu-central-1
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

plugins:
  - serverless-deployment-bucket

package:
  patterns:
    - '!./**'
    - ./bin/**
iamRoleStatements:
  - Effect: Allow
    Action:
      - "apigateway:*"
    Resource: "*"
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:ListTables
      - dynamodb:DescribeTables
    Resource: "*"
functions:
  main-module:
    handler: bin/Main
    environment:
      ENVIRONMENT: aws
      SERVICE_STAGE_NAME: sepet-main
    events:
      - http:
          path: /add-product
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /remove-product
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /empty-cart
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /get-cart
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /update-product
          method: post
          cors:
            origin: '*'
            headers: '*'

