service: sepet

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1
  deploymentBucket:
    name: sepet-deployment-bucket-eu-central-1
    blockPublicAccess: true
    versioning: true
    serverSideEncryption: AES256

plugins:
  - serverless-deployment-bucket

package:
  patterns:
    - '!./**'
    - ./bin/**
iamRoleStatements:
  - Effect: Allow
    Action:
      - "apigateway:*"
    Resource: "*"
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:ListTables
      - dynamodb:DescribeTables
    Resource: "*"
functions:
  main-module:
    handler: bin/Main
    environment:
      ENVIRONMENT: aws
      SERVICE_STAGE_NAME: sepet-main
      CART_TABLE: sepet-app-Carts
      USER_TABLE: sepet-app-Users
      PRODUCTS_TABLE: sepet-app-Products
    events:
      - http:
          path: /add-product
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /remove-product
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /empty-cart
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /get-cart
          method: get
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /update-product
          method: post
          cors:
            origin: '*'
            headers: '*'

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties: 
        TableName: sepet-app-Users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    CartTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sepet-app-Carts
        AttributeDefinitions:
          - AttributeName: cartId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: cartId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userId-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: cartId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST
    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sepet-app-Products
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST