service: sepet

provider:
  name: aws
  runtime: go1.x
  region: eu-central-1

package:
  patterns:
    - '!./**'
    - ./bin/**
functions:
  main-module:
    handler: bin/Main
    environment:
      ENVIRONMENT: aws
      SERVICE_STAGE_NAME: sepet-main
    events:
      - http:
          path: /add-product
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /remove-product
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /empty-cart
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /get-cart
          method: post
          cors:
            origin: '*'
            headers: '*'
      - http:
          path: /update-product
          method: post
          cors:
            origin: '*'
            headers: '*'

